### ISSUE TITLE
Video Display Crashes

### ISSUE THREAD

**Issue by emily29marie** [elerac/EasyPySpin#9]
When I run the video.py example, a video feed is displayed for a few seconds, but the code then crashes with the following error: 

Traceback (most recent call last):
  File "video.py", line 32, in <module>
    main()
  File "video.py", line 18, in main
    ret, frame = cap.read()
  File "/usr/local/lib/python3.8/dist-packages/EasyPySpin/videocapture.py", line 251, in read
    retval = self.grab()
  File "/usr/local/lib/python3.8/dist-packages/EasyPySpin/videocapture.py", line 201, in grab
    self.cam.BeginAcquisition()
  File "/usr/local/lib/python3.8/dist-packages/PySpin.py", line 34191, in BeginAcquisition
    return _PySpin._SWIG_CamPtr_BeginAcquisition(self)
_PySpin.SpinnakerException: Spinnaker: Camera has been removed from the list and is no longer valid. [-1002]

I'm using a grasshopper 3 camera.  Do you have any idea how I can fix this error?  Thanks,

**Comment by elerac** [comment]
Hi @emily29marie !

I have faced this problem too, but I haven't found the best solution to avoid this error. I'm using Blackfly S cameras. I sometimes find this error when the camera runs continuously for a long time (more than 30 minutes in my case).
I assume this problem is caused by a bug in Spinnaker SDK, so it looks difficult to fix it from the ground up. 
How about using _try_ and _except_ for an instant fix?
